name: Main

on:
  pull_request:
    branches: 
      - main 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
  #  The type of runner that the job will run on
    runs-on: [self-hosted, Windows, gpu]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v3
      with: 
        lfs: 'true'
    
    - name: Checkout tools repo 
      uses: actions/checkout@master
      with:
        repository: DigitalDaydreamStudios/jenkins-ue4
        path: my-tools
        
    - name: Run the build script 
      shell: powershell
      run: my-tools/build-scripts/build.ps1
      id: build_game
    

    
    
      

